### ISSUE TITLE
数据集格式请教

### ISSUE THREAD

**Issue by YangBo0411** [sgtojd/Complex-Optical-Remote-Sensing-Aircraft-Detection-Dataset#1]
作者您好!感谢您做出的杰出贡献。想在这个数据集上做实验，但是我看了一下数据集的标注格式，不是较通用的voc、coco或者YOLO格式，想请教下有通用标注格式的文件吗？或者有相应的转换代码吗？因为我也看了您对经典的算法进行了训练，想请教下您是如何操作的

**Comment by sgtojd** [comment]
我们在网盘里更新了水平框和旋转框数据集，但是注意两者图像并不是完全对应的，我们还是建议使用旋转框，因为标注的更为仔细。

**Comment by YangBo0411** [comment]
好的，明白，感谢您的杰出工作。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sgtojd/Complex-Optical-Remote-Sensing-Aircraft-Detection-Dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月4日(星期一) 晚上6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sgtojd/Complex-Optical-Remote-Sensing-Aircraft-Detection-Dataset] 数据集格式请教 (Issue #1)





 
我们在网盘里更新了水平框和旋转框数据集，但是注意两者图像并不是完全对应的，我们还是建议使用旋转框，因为标注的更为仔细。
