### ISSUE TITLE
数据集请教

### ISSUE THREAD

**Issue by YangBo0411** [sgtojd/Complex-Optical-Remote-Sensing-Aircraft-Detection-Dataset#3]
作者您好，想请教下您训练yolov5时使用的是旋转框还是水平框，水平框只有检测任务而旋转框包含了分类任务吗？我能否利用旋转框标注格式来对yolov5进行分类任务？因为看了您对数据集的介绍，包含了多种类型的飞机。

**Comment by sgtojd** [comment]
是的，目前数据集只针对检测任务，后续我们可能会构建分类识别任务数据集。

**Comment by sgtojd** [comment]
yolov5训练使用的是水平框，目前水平和旋转框都只有检测任务，我们后续可能会构建分类识别数据集。

**Comment by YangBo0411** [comment]
> 好的，明白
